name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Trigger deployment when changes are pushed to the master branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn run build:prod

      - name: Prepare deployment files
        run: |
          rm -f dist/.gitignore
          mkdir intermediate
          cp index.html intermediate/
          cp -r dist intermediate/
          grep -v "^/dist$" .gitignore > intermediate/.gitignore

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./intermediate # Directory containing index.html and dist/
          publish_branch: deploy-github-page  # Deploy to this branch